### ISSUE TITLE
Brackets Registry

### ISSUE THREAD

**Issue by sixertoy** [adobe/brackets#10760]
Hey :)

i've uploaded console-plus extension as "malas34", since i've change my username...
now i can't update it or just a new versionunder sixertoy...
i don't know if it's an username issue, becaus i've tried to upload a new zip, changing package name dans it fails

Sorry :(
Thx

**Comment by prksingh** [comment]
This is the extension you mean to update? https://github.com/sixertoy/brackets-console-plus

The registry is maintained by AboutWeb. I can try to reach someone from Aboutweb to see if they can update the permission to your new username

**Comment by sixertoy** [comment]
Yes

It would be nice :)
Of course if your are in touch with them ;)

++

**Comment by MarcelGerber** [comment]
@prksingh AFAIK, @ingorichter has admin rights to the registry too (and thus can change owners as well), so reaching out to him may be faster.

**Comment by prksingh** [comment]
I have reached out to Ingo as well. Ingo or someone from Aboutweb should be able to fix this.

**Comment by sixertoy** [comment]
Thx a lot guys :)
i should send you some French fresh "croissants au beurre" ? for apologize :D

**Comment by mtylenda** [comment]
Hey @prksingh, @MarcelGerber and @sixertoy! The server appears to have had some network connectivity issues which are now resolved. Let me know if you still have trouble uploading.

**Comment by sixertoy** [comment]
Hey @mtylenda :)
i still have some issues with my old username as "malas34"
Is there a way to fix it ?

**Comment by sixertoy** [comment]
Yo Dudes :)

I'm confused a little bit, cause i can't upload my extensions updates, i know it's my fault, may i re-upload those extensions with my new account (sixertoy) and ask you to delete all my extensions under my old username (malas34) ?

**Comment by MarcelGerber** [comment]
@dangoor has registry admin rights, too, but it looks like he's no longer part of the Brackets team as well.
It would probably be a good idea to introduce some new admins to the Brackets registry so they can operate faster.

**Comment by dangoor** [comment]
@jrowny has access. Adobe folks don't have access under usual circumstances.

**Comment by MarcelGerber** [comment]
@dangoor I thought that was part of the simple admin story?

**Comment by dangoor** [comment]
@MarcelGerber Simple admin made it way easier for people to do some administrative tasks on the registry, like changing ownership. A limited group has that access.

**Comment by sixertoy** [comment]
:)

**Comment by redmunds** [comment]
Maybe I'm mis-remembering this, but I thought that authors could go to [Brackets Registry page](https://brackets-registry.aboutweb.com/) and have simple admin capabilities on their *own* extensions. I'm currently not seeing this for my extensions.

**Comment by MarcelGerber** [comment]
@redmunds It works for me, but in this case @sixertoy changed his username and as the registry is username-based, he isn' authorized any more to administrate his own extensions.

**Comment by MiguelCastillo** [comment]
@redmunds yes you are correct, you can do a few things on your extensions.

![screenshot 2015-04-03 11 49 45](https://cloud.githubusercontent.com/assets/1457701/6984497/9506543a-d9f7-11e4-88f0-3282a357b7f2.png)

**Comment by redmunds** [comment]
My bad -- I forgot to Sign In :)

**Comment by MiguelCastillo** [comment]
@redmunds lol - that'll do it

**Comment by sixertoy** [comment]
Hello :)

I close this issue
I've switched my github's account, changed my brackets extension owner and switched back to sixertoy github account

Thanks :)
