### ISSUE TITLE
Right-clicking randomly deletes text from the editor

### ISSUE THREAD

**Issue by JordanTheriault** [adobe/brackets#11142]
Right-clicking on elements or properties will delete the text from the editor. After bisection by @humphd it's determined this is a recent regression caused by a recent commit 
 > @humphd: I bisected, and this was caused by https://github.com/adobe/brackets/commit/a0daa3a79d679201c5017529d5f0e5aa3a3232ea upstream.

Here is a screen cap of it happening.
![randomdeletion](https://cloud.githubusercontent.com/assets/5931078/7708909/40e03598-fe27-11e4-8c55-bd5f926bc79c.gif)

**Comment by abose** [comment]
Looks like a codemirror upstream issue.
@prafulVaishnav @MarcelGerber

**Comment by MarcelGerber** [comment]
Ouch.
https://github.com/codemirror/codemirror/commit/5d8347de1a6f137bf5d54659eaa2b8b6ac6b3d79 is the upstream culprit.
Let's see if it's our fault or theirs.

**Comment by MarcelGerber** [comment]
Because I might not be able to file these today, I sum up my findings here:
It looks like the content of the hidden textarea changes, which is then picked up by `slowPoll`.

I verified this is not a Chrome-only bug by successfully reproducing this in Brackets, Bracketron and [Bramble](https://bramble.mofostaging.net/) with both Chrome and Firefox.

**Comment by MarcelGerber** [comment]
That's what the stack trace looks like, with the downright nonsensical call to `applyTextInput` in the console below.

**Comment by MarcelGerber** [comment]
Upstream CM bug filed: codemirror/CodeMirror#3273

**Comment by MarcelGerber** [comment]
This is now fixed.
Thanks for reporting!

**Comment by redmoik** [comment]
Hi!

How can I fix that issue on my end? My brackets is updated but I'm still getting that bug when I right click a text.

**Comment by MarcelGerber** [comment]
Please call `git submodule sync && git submodule update --init`.

**Comment by redmoik** [comment]
I'm new to this sorry... where will I call that?

**Comment by MarcelGerber** [comment]
I guess you have a cloned version of Brackets (Is that what "updated" is for you? If not, you shouldn't ever experience this issue with a Release build).
If you have, just navigate in there `cd xyz/brackets` and then call the two commands from above.

**Comment by redmoik** [comment]
I navigated in there and typed the two commands but it gives error "no git repository,..."

I have no idea if this one is cloned or not. I just downloaded it here http://brackets.io/ and installed Code Folding plugin.

**Comment by MarcelGerber** [comment]
In that case, you don't have a clone.

So you're saying you see this exact issue in Release 1.3?

**Comment by redmoik** [comment]
I think yes. check the GIF's below

![random_delete_text_on_right_click](https://cloud.githubusercontent.com/assets/3467961/7933379/4a8cf8c6-0951-11e5-8143-4ef32d405e1d.gif)
![pluginsbracket-random_delete_text_on_right_click](https://cloud.githubusercontent.com/assets/3467961/7933381/4de08ad8-0951-11e5-8d13-5c00f11bc175.gif)

**Comment by MarcelGerber** [comment]
Indeed. Could you just quickly try `Debug > Reload without extensions`?

**Comment by redmoik** [comment]
same problem..

**Comment by redmoik** [comment]
oh wait.. Without you say? yes it's not deleting anymore when Reload without extensions

**Comment by mackenza** [comment]
it would be good to get a list of your extensions then as it seems to be an extension issue.

**Comment by abose** [comment]
The first GIF shows that it is the release build;Did you correctly launch brackets from the sources at the time?

**Comment by MarcelGerber** [comment]
@mackenza You can see it in the second GIF:
* Code Folding (the one that is now a default extension)
* Extract for Brackets
* FunctionFinder
* Smooth Scroll

@abose The thing is, he runs into this issue with his _Release_ build (but caused by some extension).
