### ISSUE TITLE
Can't install extensions

### ISSUE THREAD

**Issue by Noneatme** [adobe/brackets#12505]
I get the message "Installation Failed" : "Unknown internal error."

Xubuntu 16.04, radeon driver
Console output:

```
Download the React DevTools for a better development experience: https://fb.me/react-devtools /thirdparty/react.js:6541
PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:560:24) /utils/DeprecationWarning.js:90
9
WebSocket connection to 'ws://localhost:34839/' failed: Unexpected response code: 401 /utils/NodeConnection.js:89
WebSocket connection to 'ws://localhost:34839/' failed: Unexpected response code: 401 /utils/NodeConnection.js:89
[Extension] Error -- could not read native directory: /home/noneatme/.config/Brackets/extensions/user /utils/ExtensionLoader.js:346
Fail to nomalize Cmd-Shift-] /command/KeyBindingManager.js:580
Fail to nomalize Cmd-Shift-[ /command/KeyBindingManager.js:580
NodeSocketTransport - start /LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87
WebSocket connection to 'ws://localhost:34839/' failed: Unexpected response code: 401 /utils/NodeConnection.js:89
Unknown installation error extensionManager domain is undefined /extensibility/Package.js:411

```

What can I do?

**Comment by nethip** [comment]
Tagging @swmitra

**Comment by lukalazov** [comment]
same issue on ubuntu 16.04

**Comment by MM263** [comment]
Elementary 0.3.2

Same issue

**Comment by jsanta** [comment]
Same issue here, 
```
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04 LTS
> Release:	16.04
> Codename:	xenial
```

**Comment by pqhhl** [comment]
same issue on ubuntu 16.04

**Comment by nethip** [comment]
We are currently looking at it. Sorry for the inconvenience. We should be able to fix this and refresh the build in a day or two.

**Comment by sergo44** [comment]
Same issue on debian sid

**Comment by nethip** [comment]
There was an issue with 1.7 Linux 64 builds. It was to do with brackets unable to connect to Node. We have now fixed the problem and refreshed the builds. Could you guys download the Linux 1.7 builds again from brackets.io and check?

**Comment by pqhhl** [comment]
thanks for fix.

**Comment by CrNix** [comment]
Hi,

I've downloaded latest Brackets from the website (Release 1.7 experimental build 1.7.0-16898 (release b0a363b71) - 64 bit build ) and updated to the latest nodeJS 4.4.7 LTS and the problem still persists for me.

I can't even check for updates in Brackets or install the extensions from URL.
I am running Linux Mint 17.3 if it helps.

Should I wait for the next release or will it take some time to fix?

Thanks for any answer

**Comment by 555STi** [comment]
thanks @nethip, worked flawlessly for me.
`Linux 3.13.0-91-generic #138~precise1-Ubuntu SMP Fri Jun 24 18:50:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ficristo** [comment]
Closing since Linux build should have been fixed.
@CrNix if you are still experiencing some issue please open a new issue.
