### ISSUE TITLE
Custom font is ignored

### ISSUE THREAD

**Issue by thany** [adobe/brackets#13221]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

A custom font set in View->Themes is ignored.

### Steps to Reproduce

1. Open Brackets
2. View->Themes
3. Set any other font. In my case, Fira Code, so: `Fira Code, FiraCode, 'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace`

**Expected behavior:**
Custom font should be displayed in the editor.

**Actual behavior:**
Custom font is set, but only once, after committing the setting. After zooming in/out, after a restart, or a reload, the default font is displayed again.

### Versions

Brackets 1.9
Windows 10

This is a regression from 1.8, where setting a custom font worked just fine.

**Comment by kobezhu** [comment]
‘I’ve been through the same situation!

**Comment by prasadmudedla** [comment]
same situation... tried changing the defaultPreferneces.json.... Still no luck...

**Comment by clementi** [comment]
I'm seeing this also.

**Comment by guillecro** [comment]
This issue is already posted here,
https://github.com/adobe/brackets/issues/13205

Its not working even in Ubuntu (in my case Ubuntu 16.04 LTS x64)

**Comment by thany** [comment]
That appears to be a different issue, as it also reports the problem in 1.8.
This particular case is a *regression* from 1.8, meaning the feature worked fine in 1.8, but it broke as of 1.9.

**Comment by gxnie** [comment]
I have modified the brackets.min.css.

**Comment by thany** [comment]
Can this please be fixed with a maintenance update?

It happens too often that we need to wait 3 months or longer, for an issue to get solved in the next release. And any new release may introduce other breaking bugs, causing us to have to wait *even* longer.

**Comment by guillecro** [comment]
> Can this please be fixed with a maintenance update?

I +1 this comment. Its such annoying bug..

**Comment by jpdupont** [comment]
+1

**Comment by swmitra** [comment]
@thany We are working on this issue and hopefully have a fix by next week. Once the fix is in, we will trigger a pre-release which would be available under Brackets GitHub releases.

**Comment by vahid-sanati** [comment]
I have this bug too.

**Comment by swmitra** [comment]
Closing this as fixed by #13279 and available as part of 1.10 pre-release 1 build https://github.com/adobe/brackets/releases/tag/release-1.10-prerelease-1

**Comment by thany** [comment]
I just noticed 1.9 is still up as the latest release, even though this bug is still in there, supposedly. Why aren't you releasing this 1.10-prerelease as a maintenance update to 1.9? You can call it 1.9.1 or something.
