### ISSUE TITLE
Input Chinese character failed in ubuntu

### ISSUE THREAD

**Issue by SKYhuangjing** [adobe/brackets#13898]
OS: Ubuntu 16.04
Input: SougouPinyin, SunPinyin
Brackets: version 1.11

when I open brackets app, and prepare input something chinese,
the input can't work normal.
Example: if i wanna input **"测试"**, so I will enter **'c'**,**'e'**,**'s'**,**'h'**,**'i'** in keyborad.
Expect result: the input panel will prompt "测试", and I can choose it to brackets editor.
Actually result: the bracket editor will show **ceshi**.

Additional Info:
I have testing the same scenario in Brackets 1.9, it gives me the expect result.

**Comment by tengqian** [comment]
我也出现了这个问题 但是我是deepin 同样是不能输入中文, 重装了也不行,不知道什么问题

**Comment by kiroma** [comment]
Fairly sure it's the same bug as in #13762.
It's a bug in Chromium, which has already been patched out, only 1.11 is affected, 1.9 and 1.10 should work fine, we're currently waiting for 1.12 to release.

**Comment by nethip** [comment]
@kiroma Thanks for updating this thread. We are planning to refresh the builds with the fix in a few days time. Sorry for the inconvenience .

**Comment by nethip** [comment]
We have uploaded a pre-release build (Linux 64 only) to address this issue. Please try the build and let us know your feedback. You can download the build from https://github.com/adobe/brackets/releases/tag/release-1.12-prerelease.

**Comment by nethip** [comment]
This is fixed now. We have refreshed the Linux builds of 1.11 release. Please re-download the installers from http://brackets.io

**Comment by kentsaiforespring** [comment]
This issue remain in version 1.14.1, can anyone help?

**Comment by kentsaiforespring** [comment]
> This issue remains in version 1.14.1, can anyone help?

I found where the problem is, it's the Snap version in Ubuntu! They didn't get it fixed in their package, so the problem remains. I removed the Snap version and re-install with the downloaded .deb official version, and it worked!
